const sentencesData = [
  {
    title: "Famous Quotes",
    content: [
      "The only way to do great work is to love what you do.",
      "Life is what happens when you are busy making other plans.",
      "Get busy living or get busy dying.",
      "You have within you right now, everything you need to deal with whatever the world can throw at you.",
      "Believe you can and you're halfway there.",
    ],
    author: "Various",
    level: "Medium",
  },
  {
    title: "Proverbs",
    content: [
      "Actions speak louder than words.",
      "A journey of a thousand miles begins with a single step.",
      "All good things must come to an end.",
      "Birds of a feather flock together.",
      "Cleanliness is next to godliness.",
    ],
    author: "Traditional",
    level: "Easy",
  },
  {
    title: "Short Story: The Lion and the Mouse",
    content: [
      "A Lion lay asleep in the forest, his great head resting on his paws.",
      "A timid little Mouse came upon him unexpectedly, and in her fright and haste to get away, ran across the Lion's nose.",
      "Roused from his nap, the Lion laid his huge paw angrily on the tiny creature to kill her.",
      '"Spare me!" begged the poor Mouse.',
      '"Please let me go and some day I will surely repay you."',
    ],
    author: "Aesop",
    level: "Hard",
  },
  {
    title: "Grade 4 Essentials",
    content: [
      "I usually go to school by bus, but today I am walking.",
      "She is taller than her brother, but he is faster.",
      "We are going to visit our grandparents next weekend.",
      "Yesterday, I played soccer with my friends in the park.",
      "You should brush your teeth twice a day.",
      "The book is on the table next to the lamp.",
      "They were watching a movie when the phone rang.",
      "My favorite subject is science because I like experiments.",
      "How much water do you drink every day?",
      "If it rains tomorrow, we will stay inside.",
      "My mother is cooking dinner in the kitchen.",
      "The dog is sleeping under the big tree.",
      "We visited the zoo last Sunday.",
      "I like to read books about animals.",
      "Can you help me with my homework?",
      "It is very cold in winter, so wear a coat.",
      "She wants to be a doctor when she grows up.",
      "The sun rises in the east every morning.",
      "There are many beautiful flowers in the garden.",
      "Please turn off the lights when you leave the room.",
      "My birthday is in July, and I want a bike.",
      "He runs faster than anyone else in the class.",
      "What time do you usually wake up?",
      "I am writing a letter to my friend in London.",
      "They are playing basketball in the gym.",
      "The cat jumped onto the table and ate the fish.",
      "We should protect our environment.",
      "Do not forget to bring your umbrella.",
      "My father drives a blue car to work.",
      "I have two brothers and one sister.",
      "The library is a quiet place to study.",
      "Did you watch the football game yesterday?",
      "I am going to buy a new pair of shoes.",
      "The train leaves at eight o'clock sharp.",
      "Apples are red, but bananas are yellow.",
      "Swimming is my favorite summer activity.",
      "The baby is crying because she is hungry.",
      "We went to the beach and built a sandcastle.",
      "She can play the piano very well.",
      "Where did you put my keys?",
      "The birds are singing in the trees.",
      "I need a pencil and an eraser for the test.",
      "Let's go to the park after school.",
      "The moon shines brightly in the night sky.",
      "He is the smartest student in our grade.",
      "I drank a glass of milk for breakfast.",
      "We celebrated Christmas with our family.",
      "The teacher wrote the lesson on the blackboard.",
      "Please close the door behind you.",
      "I was sleeping when the alarm clock rang.",
      "My favorite color is blue, just like the ocean.",
      "We learned about dinosaurs in history class.",
      "The restaurant serves delicious pizza and pasta.",
      "I am looking for my lost glasses.",
      "It is important to eat vegetables every day.",
      "The spider made a web in the corner.",
      "We are learning how to speak Spanish.",
      "The movie was funny, and we laughed a lot.",
      "Be careful when you cross the street.",
      "I hope to see you again soon.",
    ],
    author: "Curriculum",
    level: "Grade 4",
  },
  {
    title: "James Clear 3-2-1",
    content: [
      "You do not rise to the level of your goals, you fall to the level of your systems.",
      "Every action you take is a vote for the type of person you wish to become.",
      "Habits are the compound interest of self-improvement.",
      "Be the designer of your world and not merely the consumer of it.",
      "The most effective way to change your habits is to focus not on what you want to achieve, but on who you wish to become.",
      "Success is the product of daily habits, not once-in-a-lifetime transformations.",
      "If you want better results, then forget about setting goals and focus on your system instead.",
      "The ultimate form of intrinsic motivation is when a habit becomes part of your identity.",
      "Standardize before you optimize.",
      "You can't optimize a habit that doesn't exist.",
      "The best way to start a new habit is to tie it to an existing one.",
      "Make it obvious, make it attractive, make it easy, make it satisfying.",
      "The quality of your life depends on the quality of your habits.",
      "Rome wasn't built in a day, but they were laying bricks every hour.",
      "Small changes eventually add up to huge results.",
      "Consistency is more important than intensity.",
      "Focus on being better, not just being good.",
      "A habit must be established before it can be improved.",
      "The only way to win is to get better every day.",
      "Your habits shape your identity, and your identity shapes your habits.",
      "Improvement is not about doing one big thing right, but doing a thousand small things better.",
      "The cost of your good habits is in the present; the cost of your bad habits is in the future.",
      "Time magnifies the margin between success and failure.",
      "Good habits make time your ally, bad habits make time your enemy.",
      "Goals are about the results you want to achieve, systems are about the processes that lead to those results.",
      "Winners and losers have the same goals.",
      "Achieving a goal is a momentary change.",
      "The purpose of setting goals is to win the game; the purpose of building systems is to continue playing the game.",
      "True long-term thinking is goal-less thinking.",
      "Atomic habits are small habits that are part of a larger system.",
      "Changes that seem small and unimportant at first will compound into remarkable results.",
      "If you can get 1 percent better each day for one year, you'll end up thirty-seven times better.",
      "Habits often appear to make no difference until you cross a critical threshold.",
      "The most powerful outcomes are delayed.",
      "Mastery requires patience.",
      "Forget about goals, focus on systems.",
      "Fix the inputs and the outputs will fix themselves.",
      "Changing our habits is challenging because we try to change the wrong thing.",
      "The first layer is changing your outcomes.",
      "The second layer is changing your process.",
      "The third layer is changing your identity.",
      "Many people begin the process of changing their habits by focusing on what they want to achieve.",
      "The alternative is to build identity-based habits.",
      "It's hard to change your habits if you never change the underlying beliefs that led to your past behavior.",
      "The goal is not to read a book, the goal is to become a reader.",
      "The goal is not to run a marathon, the goal is to become a runner.",
      "Your behaviors are usually a reflection of your identity.",
      "The more you repeat a behavior, the more you reinforce the identity associated with it.",
      "Decide the type of person you want to be.",
      "Prove it to yourself with small wins.",
      "The most practical way to change who you are is to change what you do.",
      "Habits matter because they help you become the person you wish to be.",
      "The process of building habits is actually the process of becoming yourself.",
      "A habit is a behavior that has been repeated enough times to become automatic.",
      "The ultimate purpose of habits is to solve the problems of life with as little energy and effort as possible.",
      "Any habit can be broken down into a feedback loop that involves four steps: cue, craving, response, and reward.",
      "The cue triggers your brain to initiate a behavior.",
      "Cravings are the second step of the habit loop, and they are the motivational force behind every habit.",
      "The response is the actual habit you perform, which can take the form of a thought or an action.",
      "Rewards are the end goal of every habit.",
      "If a behavior is insufficient in any of the four stages, it will not become a habit.",
      "The First Law of Behavior Change is to make it obvious.",
      "The Second Law of Behavior Change is to make it attractive.",
      "The Third Law of Behavior Change is to make it easy.",
      "The Fourth Law of Behavior Change is to make it satisfying.",
      "One of the best ways to build a new habit is to identify a current habit you already do each day.",
      "Implementation intentions leverage the two most common cues: time and location.",
      "Motivation is often overrated; environment often matters more.",
      "Environment is the invisible hand that shapes human behavior.",
      "It is easier to build new habits in a new environment because you are not fighting against old cues.",
      "Self-control is a short-term strategy, not a long-term one.",
      "The secret to self-control is to make the cues of your good habits obvious and the cues of your bad habits invisible.",
      "Habits are a dopamine-driven feedback loop.",
      "We need to make our habits attractive because it is the expectation of a rewarding experience that motivates us to act.",
      "Temptation bundling is one way to make your habits more attractive.",
      "Join a culture where your desired behavior is the normal behavior.",
      "If you want to master a habit, the key is to start with repetition, not perfection.",
      "The amount of time you have been performing a habit is not as important as the number of times you have performed it.",
      "To build a habit, you need to practice it.",
      "Human behavior follows the Law of Least Effort.",
      "We will naturally gravitate toward the option that requires the least amount of work.",
      "Create an environment where doing the right thing is as easy as possible.",
      "Reduce the friction associated with good behaviors.",
      "Increase the friction associated with bad behaviors.",
      "The Two-Minute Rule states: When you start a new habit, it should take less than two minutes to do.",
      "Standardize the beginning of the process.",
      "Make it satisfying.",
      "We are more likely to repeat a behavior when the experience is satisfying.",
      "The human brain evolved to prioritize immediate rewards over delayed rewards.",
      "The Cardinal Rule of Behavior Change: What is immediately rewarded is repeated.",
      "What is immediately punished is avoided.",
      "To get a habit to stick you need to feel immediately successful—even if it's in a small way.",
      "Never miss twice.",
      "If you miss one day, try to get back on track as quickly as possible.",
      "Missing once is an accident; missing twice is the start of a new habit.",
      "Don't break the chain.",
      "Track your habits to see your progress.",
      "The most effective form of learning is practice, not planning.",
      "Focus on the trajectory, not the position.",
      "Success is not a goal to reach, but a way of life.",
    ],
    author: "James Clear",
    level: "Advanced",
  },
];
