const poemsData = [
  {
    title: "静夜思",
    dynasty: "唐",
    author: "李白",
    content: ["床前明月光", "疑是地上霜", "举头望明月", "低头思故乡"],
  },
  {
    title: "春晓",
    dynasty: "唐",
    author: "孟浩然",
    content: ["春眠不觉晓", "处处闻啼鸟", "夜来风雨声", "花落知多少"],
  },
  {
    title: "咏鹅",
    dynasty: "唐",
    author: "骆宾王",
    content: ["鹅鹅鹅", "曲项向天歌", "白毛浮绿水", "红掌拨清波"],
  },
  {
    title: "登鹳雀楼",
    dynasty: "唐",
    author: "王之涣",
    content: ["白日依山尽", "黄河入海流", "欲穷千里目", "更上一层楼"],
  },
  {
    title: "江雪",
    dynasty: "唐",
    author: "柳宗元",
    content: ["千山鸟飞绝", "万径人踪灭", "孤舟蓑笠翁", "独钓寒江雪"],
  },
  {
    title: "相思",
    dynasty: "唐",
    author: "王维",
    content: ["红豆生南国", "春来发几枝", "愿君多采撷", "此物最相思"],
  },
  {
    title: "游子吟",
    dynasty: "唐",
    author: "孟郊",
    content: [
      "慈母手中线",
      "游子身上衣",
      "临行密密缝",
      "意恐迟迟归",
      "谁言寸草心",
      "报得三春晖",
    ],
  },
  {
    title: "悯农",
    dynasty: "唐",
    author: "李绅",
    content: ["锄禾日当午", "汗滴禾下土", "谁知盘中餐", "粒粒皆辛苦"],
  },
  {
    title: "敕勒歌",
    dynasty: "北朝民歌",
    author: "佚名",
    content: [
      "敕勒川",
      "阴山下",
      "天似穹庐",
      "笼盖四野",
      "天苍苍",
      "野茫茫",
      "风吹草低见牛羊",
    ],
  },
  {
    title: "清明",
    dynasty: "唐",
    author: "杜牧",
    content: [
      "清明时节雨纷纷",
      "路上行人欲断魂",
      "借问酒家何处有",
      "牧童遥指杏花村",
    ],
  },
];
